# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'flip_chess.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(700, 800)
        Form.setMinimumSize(QtCore.QSize(700, 800))
        Form.setMaximumSize(QtCore.QSize(700, 800))
        Form.setMouseTracking(True)
        self.chessboard_label = QtWidgets.QLabel(Form)
        self.chessboard_label.setGeometry(QtCore.QRect(22, 122, 656, 656))
        self.chessboard_label.setMinimumSize(QtCore.QSize(656, 656))
        self.chessboard_label.setMaximumSize(QtCore.QSize(656, 656))
        self.chessboard_label.setText("")
        self.chessboard_label.setObjectName("chessboard_label")
        self.current_player_img_label = QtWidgets.QLabel(Form)
        self.current_player_img_label.setGeometry(QtCore.QRect(299, 15, 71, 71))
        self.current_player_img_label.setMinimumSize(QtCore.QSize(71, 71))
        self.current_player_img_label.setMaximumSize(QtCore.QSize(71, 71))
        self.current_player_img_label.setMidLineWidth(0)
        self.current_player_img_label.setText("")
        self.current_player_img_label.setObjectName("current_player_img_label")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(10, 90, 681, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.mode_box = QtWidgets.QComboBox(Form)
        self.mode_box.setGeometry(QtCore.QRect(50, 30, 120, 50))
        self.mode_box.setMinimumSize(QtCore.QSize(120, 50))
        self.mode_box.setMaximumSize(QtCore.QSize(120, 50))
        self.mode_box.setObjectName("mode_box")
        self.restart_btn = QtWidgets.QPushButton(Form)
        self.restart_btn.setGeometry(QtCore.QRect(490, 30, 120, 50))
        self.restart_btn.setMinimumSize(QtCore.QSize(120, 50))
        self.restart_btn.setMaximumSize(QtCore.QSize(120, 50))
        self.restart_btn.setObjectName("restart_btn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.restart_btn.setText(_translate("Form", "重新开始"))
